### ISSUE TITLE
my templates are not being found

### ISSUE THREAD

**Issue by mtsbarbosa** [Dexterminator/clj-templates#5]
Hi, I've been using such pattern to define project names of my templates in order to not allocate a name of something I don't really own, so I have my organization prefix as bellow:
```clojure
;project.clj
(defproject org.clojars.majorcluster/lein-template.diplomat-http-service "0.3.0"
  :description "..."
  :url "https://github.com/mtsbarbosa/diplomat-http-service-template"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :eval-in-leiningen true)
```
usage follows as:
`lein new org.clojars.majorcluster/diplomat-http-service my-project`

Is that really supposed to not be found?

**Comment by Dexterminator** [comment]
Thanks for reporting this! Looks like a bug, I'll take a look when I can.

**Comment by Dexterminator** [comment]
This should now be fixed. Please open a new issue if you discover anything not working as it should!
